### ISSUE TITLE
Create 1.0.0 release

### ISSUE THREAD

**Issue by gabesullice** [platformsh/platformsh-nodejs-helper#2]
Nothing has been changed in this for quite some time. I think it makes sense to mark a stable release.

`npm update` won't update 0.x.y packages without forcing it to. So, when/if you _do_ release changes, even if they are BC, practically no one will get them.

**Comment by OriPekelman** [comment]
OK noted. This lib needs review before going 1.0.0 I will ask for it.

**Comment by Crell** [comment]
We're deprecating this library in favor of a brand new one, here: https://github.com/platformsh/config-reader-nodejs

It's already got a nice tag and release in npm, at version 2.0.0.  (And 2.0.1, because I goofed the npm setup a bit. :smile: )  Please migrate to that.
